keys:
  - &users:
    - &grape age1xjt7jjs0zalr6lwagldpjx07jahjpzaw7h9d46cp338speysa5asm7avgs
  - &hosts:
    - &grapepad age1s4marh347tm4aj0kjcmrlyccu4dcpqk28hvarvwy7eauml5ghd7q2fz50x
    - &grapelab age19zfu320nw9v25gxdgsn7ckpdsu8g99jpuu6yxw4y9ha4n34p24vqw2lvkk
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
        - *grape
        - *grapepad
        - *grapelab
